### ISSUE TITLE
Build failed: use of unstable library feature 'array_from_ref'

### ISSUE THREAD

**Issue by yankeexe** [Svetlitski/fcp#12]
Got this error while installing using `cargo`

![image](https://user-images.githubusercontent.com/13623913/125095228-b0093400-e0f3-11eb-9969-680222ac1f35.png)

**Comment by Svetlitski** [comment]
You need Rust 1.53.0 (the first version which stabilized `array::from_ref`) in order to build `fcp`. Try running `rustup update`, then retrying the build.
