### ISSUE TITLE
Feature request: Speed limit and IOPS limit.

### ISSUE THREAD

**Issue by vi** [Svetlitski/fcp#18]
Sometimes (especially when [the 12309](https://bugzilla.kernel.org/show_bug.cgi?id=12309) or something gets in the way) unfortunate filesystem copy operation may affect the whole system.

One of workarounds may be limiting speed.

Ideally it should support setting or changing the limit after copy operation has already started (like with `pv`).

**Comment by Svetlitski** [comment]
This will not be implemented. The express purpose of `fcp` is to copy files as fast as possible. If copying files too quickly is a concern, I would suggest using another tool.
