### ISSUE TITLE
Benchmarks question: what is copying time?

### ISSUE THREAD

**Issue by vi** [Svetlitski/fcp#19]
Benchmark plots show some time period in seconds.

What does that time mean? The time between CLI tool start and when it exits? Or the time when copying actually finishes under the hood (so e.g. removable storage can be ejected)?

Also were benchmarks performed hot (when involved data was already in RAM) or cold (e.g. like after Mac analogue of `/proc/sys/vm/drop_caches`, if it exists)?

Also how benchmarks look with NFS or removable storage?

**Comment by Svetlitski** [comment]
- The benchmarks measure copy time as the time between when the CLI tool starts and when it exits, as this is the metric which is most important to the average user. 
- The caches were warmed up prior to measurement, and left hot through the course of all runs. Feel free to peruse [the benchmark code](https://github.com/Svetlitski/fcp/blob/master/benches/fcp_benchmark.rs) for more details.
- Per the README, `fcp` is optimized for systems with an SSD. I have not profiled the tool when used with NFS or removable storage.
