### ISSUE TITLE
Request for musl build?

### ISSUE THREAD

**Issue by mathomp4** [Svetlitski/fcp#7]
I recently discovered this cool program and thought I'd try it out on the one non-laptop SSD system I have. Unfortunately:
```console
$ fcp
fcp: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by fcp)
```
In the past when I've seen things like this with Rust projects, I've asked if the developers could make a musl build instead of (or in addition to) a glibc build. Do you think `fcp` could have a musl build? Or perhaps it requires glibc? 

(Of course, it might be "I should update my OS", but it's a government system so OS updates are...let's call it deliberate in pace.)

**Comment by Svetlitski** [comment]
Sure. I built this binary inside a VM running Alpine Linux (which uses musl as its libc) using the `stable-x86_64-unknown-linux-musl` Rust toolchain. It works well within my VM (passes the tests), but just to be safe try it out yourself and make sure it works (the binary is statically linked, so I see no reason why it shouldn't). If you can confirm it works for you, I'll add it alongside the other binaries in the releases.

[fcp-0.1.0-x86_64-unknown-linux-musl.zip](https://github.com/Svetlitski/fcp/files/6718672/fcp-0.1.0-x86_64-unknown-linux-musl.zip)

**Comment by mathomp4** [comment]
@Svetlitski It seems to work! 

One question: do you think it can be `strip`ped?
```console
$ ls -ltr fcp-0.1.0-x86_64-unknown-linux-musl
-rwxr-xr-x. 1 mathomp4 users 4010488 Jun 25 16:20 fcp-0.1.0-x86_64-unknown-linux-musl*
$ strip fcp-0.1.0-x86_64-unknown-linux-musl
$ ls -ltr fcp-0.1.0-x86_64-unknown-linux-musl
-rwxr-xr-x. 1 mathomp4 users 530592 Jun 25 19:15 fcp-0.1.0-x86_64-unknown-linux-musl*
```

Unless you are still at the stages where the symbols are useful?

**Comment by Svetlitski** [comment]
Good catch, but I'd actually like to leave it as it for the present release. For context as to why, I realized only after the initial v0.1.0 release (by perusing the GitHub actions definitions of other open-source Rust projects) that I should've been stripping the binaries so they aren't huge, but the binaries were already up and it felt strange to change them without another release. So to keep things uniform between platforms, I intend to keep this musl binary unstripped. For all future releases, all binaries for all platforms will be stripped.

**Comment by mathomp4** [comment]
@Svetlitski Sounds good. And it's not like 4 MB is huge. I mean, the project I work on can make 1 GB binaries 😄 

Now I'm wondering if they ever fixed up `cargo` to build stripped binaries. Haven't looked at that in a while...

**Comment by Svetlitski** [comment]
1 GB binaries, that's quite a feat! I've gone ahead and added the musl binary to the releases page, thanks for bringing this up!
